/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package wazirx.connector.java;

import org.junit.Test;
import static org.junit.Assert.*;

public class ClientTest {
    @Test public void testSomeLibraryMethod() {
        Client classUnderTest = new Client("test", "test");
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
