/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package wazirx.connector.java;

import static org.junit.Assert.assertTrue;

import org.junit.Test;

public class ClientTest {
    @Test public void testSomeLibraryMethod() throws Exception {
        assertTrue("someLibraryMethod should return 'true'", true);
    }
}
