/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package wazirx.connector.java;

import java.util.Map;

import com.google.gson.JsonElement;

public class Client extends BaseClient {
	public Client(final String apiKey, final String secretKey) {
		super(apiKey, secretKey);
	}

	//	ping
	public JsonElement ping() throws Exception {
		return this.call("ping", null);
	}

	//	time
	public JsonElement time() throws Exception {
		return this.call("time", null);
	}

	//	system_status
	public JsonElement systemStatus() throws Exception {
		return this.call("system_status", null);
	}

	//	exchange_info
	public JsonElement exchangeInfo() throws Exception {
		return this.call("exchange_info", null);
	}

	//	tickers
	// handle case for array response
	public JsonElement tickers() throws Exception {
		return this.call("tickers", null);
	}

	//	ticker
	public JsonElement ticker(String symbol) throws Exception {
		Map<String, Object> params = Map.of("symbol", symbol);
		return this.call("ticker", params);
	}

	//	depth
	public JsonElement depth(String symbol, int limit) throws Exception {
		Map<String, Object> params = Map.of("symbol", symbol, "limit", limit);
		return this.call("depth", params);
	}

	//	trades
	public JsonElement trades(String symbol, String limit) throws Exception {
		Map<String, Object> params = Map.of("symbol", symbol, "limit", limit);
		return this.call("trades", params);
	}

	//	historical_trades
	public JsonElement historicalTrades(String symbol, String limit, int recvWindow) throws Exception {
		Map<String, Object> params = Map.of(
				"symbol", symbol,
				"limit", limit,
				"recvWindow", recvWindow,
				"timestamp", System.currentTimeMillis());
		return this.call("historical_trades", params);
	}

	//	create_order
	public JsonElement createOrder() throws Exception {
		return this.call("create_order", null);
	}

	//	create_test_order
	public JsonElement createTestOrder() throws Exception {
		return this.call("create_test_order", null);
	}

	//	query_order
	public JsonElement queryOrder() throws Exception {
		return this.call("query_order", null);
	}

	//	cancel_order
	public JsonElement cancelOrder() throws Exception {
		return this.call("cancel_order", null);
	}

	//	open_orders
	public JsonElement openOrders() throws Exception {
		return this.call("open_orders", null);
	}

	//	cancel_open_orders
	public JsonElement cancelOpenOrders() throws Exception {
		return this.call("cancel_open_orders", null);
	}

	//	all_orders
	public JsonElement allOrders() throws Exception {
		return this.call("all_orders", null);
	}

	//	account_info
	public JsonElement accountInfo() throws Exception {
		return this.call("account_info", null);
	}

	//	funds_info
	public JsonElement fundsInfo() throws Exception {
		return this.call("funds_info", null);
	}
}
