/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package wazirx.connector.java;

import java.util.Map;

public class Client extends BaseClient {
	public Client(final String apiKey, final String secretKey) {
		super(apiKey, secretKey);
	}

	//	ping
	public String ping() throws Exception {
		return this.call("ping", null);
	}

	//	time
	public String time() throws Exception {
		return this.call("time", null);
	}

	//	system_status
	public String systemStatus() throws Exception {
		return this.call("system_status", null);
	}

	//	exchange_info
	public String exchangeInfo() throws Exception {
		return this.call("exchange_info", null);
	}

	//	tickers
	// handle case for array response
	public String tickers() throws Exception {
		return this.call("tickers", null);
	}

	//	ticker
	public String ticker(String symbol) throws Exception {
		Map<String, Object> params = Map.of("symbol", symbol);
		return this.call("ticker", params);
	}

	//	depth
	public String depth(String symbol, int limit) throws Exception {
		Map<String, Object> params = Map.of("symbol", symbol, "limit", limit);
		return this.call("depth", params);
	}

	//	trades
	public String trades(String symbol, int limit) throws Exception {
		Map<String, Object> params = Map.of("symbol", symbol, "limit", limit);
		return this.call("trades", params);
	}

	//	historical_trades
	public String historicalTrades(String symbol, int limit) throws Exception {
		Map<String, Object> params = Map.of(
				"symbol", symbol,
				"limit", limit,
				"recvWindow", 10000,
				"timestamp", System.currentTimeMillis());
		return this.call("historical_trades", params);
	}

	//	create_order
	public String createOrder() throws Exception {
		return this.call("create_order", null);
	}

	//	create_test_order
	public String createTestOrder() throws Exception {
		return this.call("create_test_order", null);
	}

	//	query_order
	public String queryOrder() throws Exception {
		return this.call("query_order", null);
	}

	//	cancel_order
	public String cancelOrder() throws Exception {
		return this.call("cancel_order", null);
	}

	//	open_orders
	public String openOrders() throws Exception {
		return this.call("open_orders", null);
	}

	//	cancel_open_orders
	public String cancelOpenOrders() throws Exception {
		return this.call("cancel_open_orders", null);
	}

	//	all_orders
	public String allOrders() throws Exception {
		return this.call("all_orders", null);
	}

	//	account_info
	public String accountInfo() throws Exception {
		Map<String, Object> params = Map.of(
				"recvWindow", 20000,
				"timestamp", System.currentTimeMillis());
		return this.call("account_info", params);
	}

	//	funds_info
	public String fundsInfo() throws Exception {
		Map<String, Object> params = Map.of(
				"recvWindow", 20000,
				"timestamp", System.currentTimeMillis());
		return this.call("funds_info", params);
	}

	//	create_auth_token
	public String createAuthToken() throws Exception {
		Map<String, Object> params = Map.of(
				"recvWindow", 20000,
				"timestamp", System.currentTimeMillis());
		return this.call("create_auth_token", params);
	}
}
