/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package wazirx.connector.java;

import java.util.Map;

import com.google.gson.JsonObject;

public class Client extends BaseClient {
	public Client(final String apiKey, final String secretKey) {
		super(apiKey, secretKey);
	}

	//	ping
	public JsonObject ping() throws Exception {
		return this.call("ping", null);
	}

	//	time
	public JsonObject time() throws Exception {
		return this.call("time", null);
	}

	//	system_status
	public JsonObject systemStatus() throws Exception {
		return this.call("system_status", null);
	}

	//	exchange_info
	public JsonObject exchangeInfo() throws Exception {
		return this.call("exchange_info", null);
	}

	//	tickers
	public JsonObject tickers() throws Exception {
		return this.call("tickers", null);
	}

	//	ticker
	public JsonObject ticker(String symbol) throws Exception {
		Map<String, Object> params = Map.of("symbol", symbol);
		return this.call("ticker", params);
	}

	//	depth
	public JsonObject depth(String symbol, String limit) throws Exception {
		Map<String, Object> params = Map.of("symbol", symbol, "limit", limit);
		return this.call("depth", params);
	}

	//	trades
	public JsonObject trades(String symbol, String limit) throws Exception {
		Map<String, Object> params = Map.of("symbol", symbol, "limit", limit);
		return this.call("trades", params);
	}

	//	historical_trades
	public JsonObject historicalTrades(String symbol, String limit, int recvWindow) throws Exception {
		Map<String, Object> params = Map.of(
				"symbol", symbol,
				"limit", limit,
				"recvWindow", recvWindow,
				"timestamp", System.currentTimeMillis());
		return this.call("historical_trades", params);
	}

	//	create_order
	public JsonObject createOrder() throws Exception {
		return this.call("create_order", null);
	}

	//	create_test_order
	public JsonObject createTestOrder() throws Exception {
		return this.call("create_test_order", null);
	}

	//	query_order
	public JsonObject queryOrder() throws Exception {
		return this.call("query_order", null);
	}

	//	cancel_order
	public JsonObject cancelOrder() throws Exception {
		return this.call("cancel_order", null);
	}

	//	open_orders
	public JsonObject openOrders() throws Exception {
		return this.call("open_orders", null);
	}

	//	cancel_open_orders
	public JsonObject cancelOpenOrders() throws Exception {
		return this.call("cancel_open_orders", null);
	}

	//	all_orders
	public JsonObject allOrders() throws Exception {
		return this.call("all_orders", null);
	}

	//	account_info
	public JsonObject accountInfo() throws Exception {
		return this.call("account_info", null);
	}

	//	funds_info
	public JsonObject fundsInfo() throws Exception {
		return this.call("funds_info", null);
	}
}
